ADVISORY_MODE = True
ADVISORY_ENGINE_VERSION = "v1.0"
ADVISORY_CONTRACT_VERSION = "1.0"

STATUS = {
    "ACTIVE": "ACTIVE",
    "BLOCKED": "BLOCKED",
    "LEGACY": "LEGACY",
    "ERROR": "ERROR",
}

HEALTH_BANDS = {
    "strong": (70, 100),
    "moderate": (40, 70),
    "fragile": (0, 40),
}

CONFIDENCE_BANDS = {
    "high": (0.7, 1.0),
    "medium": (0.4, 0.7),
    "low": (0.0, 0.4),
}

EMI_RATIO_THRESHOLD = 0.4
EMERGENCY_FUND_BLOCK_MONTHS = 3
EMERGENCY_FUND_GUARDRAIL_MONTHS = 6
LIFE_COVER_EQUITY_CAP = 30.0
EMERGENCY_FUND_EQUITY_MULTIPLIER = 0.7
EMI_EQUITY_MULTIPLIER = 0.6
ALLOCATION_TOLERANCE = 0.5
CONFIDENCE_STRESS_PENALTY = 0.85
